version: "3"
services:
  app:
    container_name: arabic-roman-calc
    build: ./
    ports:
      - "3000:3000"
    volumes:
      - ./src:/usr/app/src
      - ./public:/usr/app/public
    tty: true
